// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxS2Kc5j46iaxGxNb2YAsN0Ln1FN_HUQk',
    appId: '1:261732256114:web:9734f5a56529dba5e375eb',
    messagingSenderId: '261732256114',
    projectId: 'savebite-1fd01',
    authDomain: 'savebite-1fd01.firebaseapp.com',
    storageBucket: 'savebite-1fd01.firebasestorage.app',
    measurementId: 'G-5KZRNDKKCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV-yzXVAMp9n4_--zkqB69WjzWE0kTOHM',
    appId: '1:261732256114:android:11f69ba8670bf201e375eb',
    messagingSenderId: '261732256114',
    projectId: 'savebite-1fd01',
    storageBucket: 'savebite-1fd01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-2Q3ffhtnzIrE27guC31yaLvlav8Nm0',
    appId: '1:261732256114:ios:76a8c6b4a2aaa9c8e375eb',
    messagingSenderId: '261732256114',
    projectId: 'savebite-1fd01',
    storageBucket: 'savebite-1fd01.firebasestorage.app',
    iosBundleId: 'com.example.savebite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-2Q3ffhtnzIrE27guC31yaLvlav8Nm0',
    appId: '1:261732256114:ios:76a8c6b4a2aaa9c8e375eb',
    messagingSenderId: '261732256114',
    projectId: 'savebite-1fd01',
    storageBucket: 'savebite-1fd01.firebasestorage.app',
    iosBundleId: 'com.example.savebite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxS2Kc5j46iaxGxNb2YAsN0Ln1FN_HUQk',
    appId: '1:261732256114:web:228a8f5539ea2635e375eb',
    messagingSenderId: '261732256114',
    projectId: 'savebite-1fd01',
    authDomain: 'savebite-1fd01.firebaseapp.com',
    storageBucket: 'savebite-1fd01.firebasestorage.app',
    measurementId: 'G-L7D7P2R4K2',
  );
}
